/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.hospital.patientrole;

import business.drug.Drug;
import business.workqueue.WorkRequestDoctor;
import business.workqueue.WorkRequestDrugs;
//import static com.oracle.util.Checksums.update;
import commonutils.Constants;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import userinterface.chemist.workerrole.ViewEditDrugsOrderJpanel;
import userinterface.chemist.workerrole.WorkerWorkAreaJPanel;

/**
 *
 * @author JAINHEMANT
 */
public class ViewEditDrugsPatientsOrderJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEditDrugsPatientsOrderJpanel
     */
    
    private JPanel userProcessContainer;
    private WorkRequestDoctor workRequestDoctor;
    private static final Logger log = LogManager.getLogger(ViewEditDrugsOrderJpanel.class);
  

   public ViewEditDrugsPatientsOrderJpanel(JPanel userProcessContainer, WorkRequestDoctor request, boolean orderProc) {
       initComponents();
        ((DefaultTableCellRenderer) drugquantity.getDefaultRenderer(Object.class)).setOpaque(false);
     
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        drugquantity.setEnabled(false);
        drugquantity.setSize(300, 64);
        this.userProcessContainer = userProcessContainer;
        this.workRequestDoctor = request;
        drugquantity.setShowGrid(true);
        //drugquantity.getTableHeader().setOpaque(false);
        // drugquantity.getTableHeader().setBackground(Color.BLUE);
        //drugquantity.getTableHeader().setForeground(Color.BLACK);

        //JTableHeader tableHeader = drugquantity.getTableHeader();
        //tableHeader.setBackground(Color.red);
        this.setSize(1200, 750);
      //  this.userProcessContainer = userProcessContainer;
      //  this.workRequestDrugs = workRequestDrugs;
       
        populateRequestTable();
    }

    public void populateRequestTable() {
        drugquantity1.getTableHeader().setFont(new Font("Segoe UI", 1, 20));
        DefaultTableModel model = (DefaultTableModel) drugquantity1.getModel();
 System.out.println(workRequestDoctor.getDrugsOrderList()+"LIST");
        model.setRowCount(0);
        for (Drug drug : workRequestDoctor.getDrugsOrderList()) {
            System.out.println(drug+"DRUGG");
            Object[] row = new Object[2];
            row[0] = drug;
            row[1] = Integer.toString(drug.getQuantity());
            model.addRow(row);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        drugquantity = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugquantity1 = new javax.swing.JTable();
        backJButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        drugquantity.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Quantity"
            }
        ));
        drugquantity.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(drugquantity);

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("View and Update Order Details");
        jLabel1.setAlignmentX(740.0F);
        jLabel1.setAlignmentY(245.0F);
        add(jLabel1);
        jLabel1.setBounds(270, 70, 560, 48);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        drugquantity1.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        drugquantity1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Quantity"
            }
        ));
        drugquantity1.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity1.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(drugquantity1);

        add(jScrollPane2);
        jScrollPane2.setBounds(210, 130, 700, 230);

        backJButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/arrow-back-icon_1_40x40.png"))); // NOI18N
        backJButton1.setContentAreaFilled(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1);
        backJButton1.setBounds(20, 40, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/patient.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        add(jLabel2);
        jLabel2.setBounds(2, 0, 1080, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JTable drugquantity;
    private javax.swing.JTable drugquantity1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
