/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.manufacturer.producerrole;

import business.EcoSystem;
import business.drug.Drug;
import business.workqueue.WorkRequestDrugs;
import commonutils.Constants;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author NEERAJ PREMANI
 */
public class ViewAndUpdateBidProducerjpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderjpanel
     */
    private JPanel userProcessContainer;
    private WorkRequestDrugs workRequestDrugs;
    private EcoSystem ecoSystem;

    private static final Logger log = LogManager.getLogger(ViewAndUpdateBidProducerjpanel.class);

    public ViewAndUpdateBidProducerjpanel(JPanel userProcessContainer, WorkRequestDrugs request, EcoSystem system) {
        initComponents();
        this.setSize(1200, 750);
        ((DefaultTableCellRenderer) drugquantity.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        this.userProcessContainer = userProcessContainer;
        this.workRequestDrugs = request;
        this.ecoSystem = system;
        populateRequestTable();
        log.info("ViewAndUpdateBidProducerjpanel loaded successfully");

    }

    public void populateRequestTable() {
         drugquantity.getTableHeader().setFont(new Font("Segoe UI", 1, 20));
        DefaultTableModel model = (DefaultTableModel) drugquantity.getModel();

        model.setRowCount(0);
        for (Drug drug : workRequestDrugs.getDrugsOrderList()) {
            Object[] row = new Object[3];
            row[0] = drug;
            row[1] = drug.getRequestCountFromMan();
            if (drug.getManufacturerPrice() > 0) {
                row[2] = drug.getManufacturerPrice();
            }

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugquantity = new javax.swing.JTable();
        jButtonCheckInventory = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugquantity1 = new javax.swing.JTable();
        jButtonCheckInventory1 = new javax.swing.JButton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        drugquantity2 = new javax.swing.JTable();
        jButtonCheckInventory2 = new javax.swing.JButton();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        drugquantity3 = new javax.swing.JTable();
        jButtonCheckInventory3 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 750));

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(183, 248, 230));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1200, 750));
        kGradientPanel1.setLayout(null);

        drugquantity.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        drugquantity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugquantity.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(drugquantity);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(156, 179, 612, 231);

        jButtonCheckInventory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCheckInventory.setText("Submit");
        jButtonCheckInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInventoryActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButtonCheckInventory);
        jButtonCheckInventory.setBounds(425, 428, 87, 31);

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(183, 248, 230));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1200, 750));
        kGradientPanel2.setLayout(null);

        drugquantity1.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugquantity1.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity1.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(drugquantity1);

        kGradientPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(156, 179, 612, 231);

        jButtonCheckInventory1.setText("Submit");
        jButtonCheckInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInventory1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButtonCheckInventory1);
        jButtonCheckInventory1.setBounds(425, 428, 73, 25);

        kGradientPanel3.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(183, 248, 230));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(1200, 750));
        kGradientPanel3.setLayout(null);

        drugquantity2.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugquantity2.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity2.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(drugquantity2);

        kGradientPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(156, 179, 612, 231);

        jButtonCheckInventory2.setText("Submit");
        jButtonCheckInventory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInventory2ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jButtonCheckInventory2);
        jButtonCheckInventory2.setBounds(425, 428, 73, 25);

        kGradientPanel4.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(183, 248, 230));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(1200, 750));
        kGradientPanel4.setLayout(null);

        drugquantity3.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugquantity3.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity3.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity3.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(drugquantity3);

        kGradientPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(156, 179, 612, 231);

        jButtonCheckInventory3.setText("Submit");
        jButtonCheckInventory3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInventory3ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(jButtonCheckInventory3);
        jButtonCheckInventory3.setBounds(425, 428, 73, 25);

        backJButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/arrow-back-icon_1_40x40.png"))); // NOI18N
        backJButton1.setContentAreaFilled(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(backJButton1);
        backJButton1.setBounds(20, 40, 50, 40);

        title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title1.setText("Order Drugs");
        title1.setAlignmentX(740.0F);
        title1.setAlignmentY(245.0F);
        kGradientPanel4.add(title1);
        title1.setBounds(290, 60, 270, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/patient.jpg"))); // NOI18N
        jLabel5.setText("jLabel1");
        kGradientPanel4.add(jLabel5);
        jLabel5.setBounds(-80, -30, 1360, 820);

        kGradientPanel3.add(kGradientPanel4);
        kGradientPanel4.setBounds(0, 0, 1200, 750);

        kGradientPanel2.add(kGradientPanel3);
        kGradientPanel3.setBounds(0, 0, 1200, 750);

        kGradientPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(0, 0, 1200, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCheckInventory3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInventory3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckInventory3ActionPerformed

    private void jButtonCheckInventory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInventory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckInventory2ActionPerformed

    private void jButtonCheckInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInventory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckInventory1ActionPerformed

    private void jButtonCheckInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInventoryActionPerformed

        List<Drug> orderList = new ArrayList<>();
        try {
            DefaultTableModel model = (DefaultTableModel) drugquantity.getModel();
            int nRow = model.getRowCount();
            for (int i = 0; i < nRow; i++) {
                if (model.getValueAt(i, 0) != null && model.getValueAt(i, 1) != null) {
                    String drugName = String.valueOf(model.getValueAt(i, 0));
                    //int drugRequested = (Integer) model.getValueAt(i, 1);
                    double manufacturerPrice = (Double) model.getValueAt(i, 2);
                    if(manufacturerPrice <= 0){
                        JOptionPane.showMessageDialog(null, "Quantiy should be greater than zero.");
                        return;
                    }

                    for (Drug drug : workRequestDrugs.getDrugsOrderList()) {
                        if (drug.getName().equalsIgnoreCase(drugName)) {
                            drug.setManufacturerPrice(manufacturerPrice);
                            break;
                        }
                    }

                }

            }
            workRequestDrugs.setStatus(Constants.priceUpdatedByManufacturer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter decimal value in price field.");
            log.error("Please enter decimal value in price field.", e);
            //e.printStackTrace();
            return;
        }

        JOptionPane.showMessageDialog(null, "Price updated successfully");
        log.info("Price updated successfully");
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProducerWorkAreaJPanel producerWorkAreaJPanel = (ProducerWorkAreaJPanel) component;
        producerWorkAreaJPanel.populateRequestTable();

        // Taking the user back to the previous screen
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonCheckInventoryActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JTable drugquantity;
    private javax.swing.JTable drugquantity1;
    private javax.swing.JTable drugquantity2;
    private javax.swing.JTable drugquantity3;
    private javax.swing.JButton jButtonCheckInventory;
    private javax.swing.JButton jButtonCheckInventory1;
    private javax.swing.JButton jButtonCheckInventory2;
    private javax.swing.JButton jButtonCheckInventory3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
