/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.hospital.doctorrole;

import business.EcoSystem;
import userinterface.chemist.workerrole.*;
import business.drug.Drug;
import business.enterprise.ChemistEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.HospitalEnterprise;
import business.enterprise.SupplierEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.chemist.WorkerOrganization;
import business.organization.hospital.DoctorOrganization;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import business.workqueue.WorkRequestDoctor;
import business.workqueue.WorkRequestDrugs;
import commonutils.Constants;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author JAINHEMANT
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderDrugsJpanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private WorkRequest request;
    private EcoSystem ecosystem;
    Network networkSelected = new Network();
    List<Enterprise> enterpriseList = new ArrayList<>();
    private static final Logger log = LogManager.getLogger(ProcessRequestJPanel.class);

    public ProcessRequestJPanel(JPanel userProcessContainer, Organization organization, EcoSystem ecosystem, UserAccount userAccount, WorkRequestDoctor request, Enterprise enterprise) {
        initComponents();
        this.setSize(1200, 750);
        ((DefaultTableCellRenderer) drugquantity.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        networkDropdown.removeAllItems();
//        enterpriseDropdown.removeAllItems();
        this.organization = (DoctorOrganization) organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.request = (WorkRequestDoctor) request;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        List<Network> networkList = ecosystem.getNetworkDirectory().getNetworkList();
        networkList.stream().forEach(network -> networkDropdown.addItem(network.getName()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugquantity = new javax.swing.JTable();
        addRow = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkDropdown = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(183, 248, 230));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1200, 750));
        kGradientPanel1.setLayout(null);

        drugquantity.setBackground(new java.awt.Color(153, 255, 255));
        drugquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugquantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        drugquantity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Quantity"
            }
        ));
        drugquantity.setGridColor(new java.awt.Color(0, 0, 0));
        drugquantity.setSelectionBackground(new java.awt.Color(153, 255, 255));
        drugquantity.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(drugquantity);

        kGradientPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 210, 519, 231);

        addRow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRow.setText("Add Row");
        addRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowActionPerformed(evt);
            }
        });
        kGradientPanel1.add(addRow);
        addRow.setBounds(690, 460, 120, 31);

        submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(submit);
        submit.setBounds(270, 460, 110, 31);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setAlignmentX(740.0F);
        jLabel1.setAlignmentY(245.0F);
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(1017, 391, 0, 0);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Order Drugs");
        jLabel2.setAlignmentX(740.0F);
        jLabel2.setAlignmentY(245.0F);
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(180, 30, 230, 50);

        networkDropdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkDropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                networkDropdownItemStateChanged(evt);
            }
        });
        networkDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkDropdownActionPerformed(evt);
            }
        });
        kGradientPanel1.add(networkDropdown);
        networkDropdown.setBounds(380, 130, 160, 28);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Network:");
        jLabel4.setAlignmentX(740.0F);
        jLabel4.setAlignmentY(245.0F);
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(279, 130, 100, 30);

        backJButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/arrow-back-icon_1_40x40.png"))); // NOI18N
        backJButton1.setContentAreaFilled(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(backJButton1);
        backJButton1.setBounds(20, 40, 50, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/doctor.jpg"))); // NOI18N
        jLabel6.setText("jLabel1");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(-150, 0, 1390, 750);

        add(kGradientPanel1);
        kGradientPanel1.setBounds(-10, -10, 1200, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        List<Drug> orderList = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) drugquantity.getModel();
        int nRow = model.getRowCount();
        System.out.println("Process Started");
        WorkRequestDoctor wreDoctor=(WorkRequestDoctor)request;
        try {
            for (int i = 0; i < nRow; i++) {
                if (!(model.getValueAt(i, 0).equals("") || model.getValueAt(i, 1).equals(""))) {
                    String drugName = String.valueOf(model.getValueAt(i, 0));
                    if (orderList.stream().noneMatch(d -> d.getName().equalsIgnoreCase(drugName))) {
                        Drug newDrug = new Drug();
                        newDrug.setName(String.valueOf(model.getValueAt(i, 0)));
                        int quantity = Integer.parseInt((String) model.getValueAt(i, 1));
                        if (quantity <= 0) {
                            JOptionPane.showMessageDialog(null, "Quantiy should be greater than zero.");
                            return;
                        }
                        newDrug.setQuantity(quantity);
                        orderList.add(newDrug);
                        JOptionPane.showMessageDialog(null, "Drug added Successfully.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Double entries of " + drugName + " is not allowed.");
                        return;
                    }
                } else {
                    if (!(model.getValueAt(i, 0).equals("") && model.getValueAt(i, 1).equals(""))) {
                        if (model.getValueAt(i, 0).equals("")) {
                            JOptionPane.showMessageDialog(null, "Enter drug name");
                            return;
                        } else {
                            JOptionPane.showMessageDialog(null, "Enter quantity of drug");
                            return;
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter integer value in quantity field.");
            return;
        }

        System.out.println("WORKER DRUG REQ  " + orderList);
        if (!orderList.isEmpty()) {
            for (Enterprise e : enterpriseList) {
                Organization org = null;
                for (Organization organization1 : e.getOrganizationDirectory().getOrganizationList()) {
                    if (organization1 instanceof WorkerOrganization) {
                        org = organization1;
                    }

                    System.out.println("WORKER ORG CHECKKK:  " + org);

                    if (org != null) {
                        WorkRequestDrugs workRequestDrugs = new WorkRequestDrugs(request.getRequestId());
                        org.getWorkQueue().getWorkRequestList().add(workRequestDrugs);
                         System.out.println("Second PRocess Doctor ID "+request.getRequestId());
                        workRequestDrugs.setSender(userAccount);
                        workRequestDrugs.setStatus(Constants.chemistCoworkerRequestCreated);
                        workRequestDrugs.setDrugsOrderList(orderList);
                        wreDoctor.setDrugsOrderList(orderList);
                        wreDoctor.setStatus(Constants.chemistCoworkerRequestCreated);
                        System.out.println("Doctor table Order: " + org.getWorkQueue().getWorkRequestList());
                        log.info("Doctor Prescribed");
//                        userProcessContainer.remove(this);
//                        Component[] componentArray = userProcessContainer.getComponents();
//                        Component component = componentArray[componentArray.length - 1];
//                        DoctorWorkAreaJPanel doctorworkareajpanel = (DoctorWorkAreaJPanel) component;
//                        doctorworkareajpanel.populateDoctorTable();
                            drugquantity.getTableHeader().setFont(new Font("Segoe UI", 1, 20));

//                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//                        layout.previous(userProcessContainer);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Order list can't be empty.");
            return;
        }
    }//GEN-LAST:event_submitActionPerformed

    private void addRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowActionPerformed
        DefaultTableModel model = (DefaultTableModel) drugquantity.getModel();
        model.addRow(new Object[]{"", ""});
    }//GEN-LAST:event_addRowActionPerformed

    private void networkDropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_networkDropdownItemStateChanged
        // TODO add your handling code here:
//        enterpriseDropdown.removeAllItems();
        if (ecosystem != null) {
            List<Network> networkList = ecosystem.getNetworkDirectory().getNetworkList();
            String networkName = networkDropdown.getSelectedItem().toString();
            networkSelected = networkList.stream()
                    .filter(network -> networkName.equals(network.getName()))
                    .findAny()
                    .orElse(null);
        }

        if (networkSelected != null) {
            enterpriseList = networkSelected.getEnterpriseDirectory().getEnterpriseList().stream().
                    filter(enterprise -> enterprise instanceof ChemistEnterprise).collect(Collectors.toList());
        }
       
    }//GEN-LAST:event_networkDropdownItemStateChanged

    private void networkDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkDropdownActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRow;
    private javax.swing.JButton backJButton1;
    private javax.swing.JTable drugquantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JComboBox<String> networkDropdown;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
