/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;
import Business.*;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author VARSHA PREMANI
 */

public class TravelAgencyPanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    private AirlinerDirectory airDir;
    private CustomerDirectory cusDir;
    private FleetDirectory fleeDir;
    private BookingDirectory bookDir;

    /**
     * Creates new form TravelAgencyPanel
     */
    public TravelAgencyPanel(JPanel rightPanel, AirlinerDirectory airDir, CustomerDirectory cusDir,FleetDirectory fleeDir,BookingDirectory bookDir ) {
        initComponents();
        this.rightPanel= rightPanel;
        this.airDir = airDir ;
        this.cusDir = cusDir ;
        this.fleeDir = fleeDir ;
        this.bookDir=bookDir;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageAirBtn = new javax.swing.JButton();
        manageCusBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        airlinesBookedTicketsBtn = new javax.swing.JButton();

        manageAirBtn.setText("Manage Airliners");
        manageAirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirBtnActionPerformed(evt);
            }
        });

        manageCusBtn.setText("Manage Customers");
        manageCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCusBtnActionPerformed(evt);
            }
        });

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        airlinesBookedTicketsBtn.setText("Airlines Booked Tickets");
        airlinesBookedTicketsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinesBookedTicketsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageAirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(airlinesBookedTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageAirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlinesBookedTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirBtnActionPerformed
        // TODO add your handling code here:        
        ManageAirJPanel maPanel = new ManageAirJPanel(rightPanel, airDir, fleeDir);
        rightPanel.add("ManageAirJPanel",maPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_manageAirBtnActionPerformed

    private void manageCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCusBtnActionPerformed
        // TODO add your handling code here:       
        ManageCusJPanel mcPanel = new ManageCusJPanel(rightPanel, cusDir);
        rightPanel.add("ManageCusJPanel",mcPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_manageCusBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void airlinesBookedTicketsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinesBookedTicketsBtnActionPerformed
        // TODO add your handling code here:
        AirlinesBookedTicketsJPanel mcPanel = new AirlinesBookedTicketsJPanel(rightPanel, bookDir,airDir);
        rightPanel.add("AirlinesBookedTicketsJPanel",mcPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_airlinesBookedTicketsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlinesBookedTicketsBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manageAirBtn;
    private javax.swing.JButton manageCusBtn;
    // End of variables declaration//GEN-END:variables
}
