/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author VARSHA PREMANI
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {
    private CustomerDirectory cusDir;
    private Customer cust;
    private JPanel rightPanel;
    /**
     * Creates new form ViewCustomerJPanel
     */
    public ViewCustomerJPanel(JPanel rightPanel,Customer cust, CustomerDirectory cusDir) {
        initComponents();
        this.cusDir = cusDir ;
        this.cust = cust;
        this.rightPanel = rightPanel ;
        
        customerNamejTextField.setText(cust.getCustomerName());
        customerEmailjTextField.setText(cust.getCustomerEmail());
        customerPhonljTextField.setText(cust.getPhone());
        if (cust.getGender().equalsIgnoreCase("Male")){
            maleRadioBtn.setSelected(true);
        }       
        else if (cust.getGender().equalsIgnoreCase("Female")){
            femaleRadioBtn.setSelected(true);
        }
        customerNamejTextField.setEditable(false);
        customerEmailjTextField.setEditable(false);
        customerPhonljTextField.setEditable(false);
        saveBtn.setEnabled(false);
        maleRadioBtn.setEnabled(false);
        femaleRadioBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private boolean usernamePatternCorrect()
    {
        Pattern p=Pattern.compile("^[a-zA-Z0-9]+.[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m=p.matcher(customerEmailjTextField.getText());
        boolean b=m.matches();
        return b;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customerEmailjTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        customerPhonljTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Name* :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Email* :");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updBtn.setText("Update");
        updBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Gender* :");

        buttonGroup1.add(maleRadioBtn);
        maleRadioBtn.setText("Male");

        buttonGroup1.add(femaleRadioBtn);
        femaleRadioBtn.setText("Female");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Phone* :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(saveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femaleRadioBtn))
                            .addComponent(customerPhonljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioBtn)
                    .addComponent(femaleRadioBtn)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerPhonljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(updBtn)
                    .addComponent(saveBtn))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        customerNamejTextField.setEditable(false);
        customerEmailjTextField.setEditable(false);
        customerPhonljTextField.setEditable(false);
        maleRadioBtn.setEnabled(false);
        femaleRadioBtn.setEnabled(false);
        updBtn.setEnabled(true);
        if (customerNamejTextField.getText().trim().isEmpty() ||
            customerEmailjTextField.getText().trim().isEmpty() ||
            customerPhonljTextField.getText().trim().isEmpty()
        )
        {
            JOptionPane.showMessageDialog(null, "Please fill manadatory fields");
            return;
        }
        
        if(!usernamePatternCorrect())
        {
            JOptionPane.showMessageDialog(null, "Please enter in format aa.bb@gmail.com");
            return;      
        }
        if (customerPhonljTextField.getText().trim().length() != 10)
        {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number");
            return;
        }
//        if (femaleRadioBtn.isSelected()){
//            if (maleRadioBtn.isSelected()){
//                JOptionPane.showMessageDialog(this, "Please select appropriate gender");
//                return;
//            }
//        }
//        else if  (maleRadioBtn.isSelected())
//         {
//         }
//        else {
//            JOptionPane.showMessageDialog(this, "Please select appropriate gender");
//            return;
//        }

       if (femaleRadioBtn.isSelected()){
            cust.setGender("Female");           
        }
       else if (maleRadioBtn.isSelected()){
            cust.setGender("Male");           
        }
        cust.setCustomerName(customerNamejTextField.getText().trim());
        cust.setCustomerEmail(customerEmailjTextField.getText().trim());
        cust.setPhone(customerPhonljTextField.getText());        
        JOptionPane.showMessageDialog(null, "Customer Information Updated Successfully");
        
         rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
        Component[] components = rightPanel.getComponents();
        for(Component c : components){
            if(c instanceof ManageCusJPanel){
                ManageCusJPanel panel = (ManageCusJPanel)c;
                panel.populate();
            }
    }           
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed
        // TODO add your handling code here:
        customerNamejTextField.setEditable(true);
        customerEmailjTextField.setEditable(true); 
        customerPhonljTextField.setEditable(true);
        maleRadioBtn.setEnabled(true);
        femaleRadioBtn.setEnabled(true);  
        saveBtn.setEnabled(true);
        updBtn.setEnabled(false);
    }//GEN-LAST:event_updBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
        Component[] components = rightPanel.getComponents();
        for(Component c : components){
            if(c instanceof ManageCusJPanel){
                ManageCusJPanel panel = (ManageCusJPanel)c;
                panel.populate();
            }
    }//GEN-LAST:event_backBtnActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField customerEmailjTextField;
    private javax.swing.JTextField customerNamejTextField;
    private javax.swing.JTextField customerPhonljTextField;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updBtn;
    // End of variables declaration//GEN-END:variables
}
