/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;


import Business.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author jaysh
 */
public class BookingDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingDetailJPanel
     */

    private JPanel rightPanel;
    private Customer customer;
    private FlytSchedule flsch;
    private FlytScheduleDirectory fschDir;
    private BookingDirectory bookDir;
    private Booking booking;
    private Seats seats;

      public BookingDetailJPanel(JPanel rightPanel,Customer customer,FlytSchedule flsch,BookingDirectory bookDir,FlytScheduleDirectory fschDir) {
        initComponents();
        this.rightPanel = rightPanel ;
        this.bookDir = bookDir;
        this.fschDir = fschDir;
        this.customer = customer;
        this.flsch = flsch;
        this.seats= seats;
        Booking booking = new Booking();
        custNameTextField.setText(customer.getCustomerName());
        custEmailTextField.setText(customer.getCustomerEmail());
        flytNumTextField.setText(flsch.getFlytNum());
        flytFromTextField.setText(flsch.getFlytFrom());
        flytToTextField.setText(flsch.getFlytTo());
        flytDateTextField.setText(flsch.getFlytDate());
        flyTimeTextField.setText(flsch.getFlytTime());
        flytSeatNumTextField.setText("");
        flytBookingIdTextField.setText(String.valueOf(booking.getFlytBookingId()));
        modifyBookingBtn.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        flytNumTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        flytFromTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        flytToTextField = new javax.swing.JTextField();
        flytDateTextField = new javax.swing.JTextField();
        flytSeatNumTextField = new javax.swing.JTextField();
        flytBookingIdTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        bookBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        custEmailTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        wRadioBtn = new javax.swing.JRadioButton();
        mRadioBtn = new javax.swing.JRadioButton();
        aRadioBtn = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        flyTimeTextField = new javax.swing.JTextField();
        modifyBookingBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel13.setText("To :");

        jLabel14.setText("Date :");

        flytNumTextField.setEditable(false);

        jLabel4.setText("Booking Id :");

        flytFromTextField.setEditable(false);

        jLabel15.setText("Seat :");

        flytToTextField.setEditable(false);

        flytDateTextField.setEditable(false);

        flytSeatNumTextField.setEditable(false);

        flytBookingIdTextField.setEditable(false);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        bookBtn.setText("Book");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Customer Email :");

        custEmailTextField.setEditable(false);

        jLabel9.setText("Customer Name :");

        custNameTextField.setEditable(false);

        jLabel10.setText("Seat Preference :");

        buttonGroup1.add(wRadioBtn);
        wRadioBtn.setText("Window");

        buttonGroup1.add(mRadioBtn);
        mRadioBtn.setText("Middle");

        buttonGroup1.add(aRadioBtn);
        aRadioBtn.setText("Aisle");

        jLabel11.setText(" Flight Time :");

        flyTimeTextField.setEditable(false);

        modifyBookingBtn.setText("Cancel  Booking");
        modifyBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBookingBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("From  :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking Details");

        jLabel2.setText("Flight No. :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(modifyBookingBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bookBtn))
                            .addComponent(backBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel8)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(flytDateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(flytToTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(flytFromTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(flytNumTextField)
                                    .addComponent(custEmailTextField)
                                    .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(flytSeatNumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(flyTimeTextField)
                                    .addComponent(flytBookingIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aRadioBtn)
                            .addComponent(mRadioBtn)
                            .addComponent(wRadioBtn))))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(custEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(flytNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flytFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flytToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flytDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wRadioBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flytSeatNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(mRadioBtn)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flytBookingIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aRadioBtn)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(flyTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookBtn)
                    .addComponent(modifyBookingBtn))
                .addGap(22, 22, 22)
                .addComponent(backBtn)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
        Component[] components = rightPanel.getComponents();
        for(Component c : components){
            if(c instanceof AvlFlytJPanel){
                AvlFlytJPanel panel = (AvlFlytJPanel)c;
             //   panel.populate();
            }
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:

        Booking book = bookDir.addBooking();
        if (wRadioBtn.isSelected())
        {
            Seats seats =  flsch.searchSeat("W");
            if( seats == null){
                JOptionPane.showMessageDialog(null,"No windows seats found");
                return;
            }else{
                flytSeatNumTextField.setText(String.valueOf(seats.getSeatNum()));
                seats.setSeatStatus("U");

            }
        }
        else if (mRadioBtn.isSelected())
        {
            Seats seats =  flsch.searchSeat("M");
            if( seats == null){
                JOptionPane.showMessageDialog(null,"No middle seats found");
                return;
            }else{
                flytSeatNumTextField.setText(String.valueOf(seats.getSeatNum()));
                seats.setSeatStatus("U");

            }
        }
        else if (aRadioBtn.isSelected())
        {
            Seats seats =  flsch.searchSeat("A");
            if( seats == null){
                JOptionPane.showMessageDialog(null,"No aisle seats found");
            }else{
                flytSeatNumTextField.setText(String.valueOf(seats.getSeatNum()));
                seats.setSeatStatus("U");

            }
        }
        book.setFlytCustName(custNameTextField.getText());
        book.setFlytSeatNum(Integer.parseInt(flytSeatNumTextField.getText()));
        book.setFlytBookingId(Integer.parseInt(flytBookingIdTextField.getText()));
        book.setFlytNum(flytNumTextField.getText());
        book.setFlytFrom(flytFromTextField.getText());
        book.setFlytTo(flytToTextField.getText());
        book.setFlytCustEmail(custEmailTextField.getText());
        book.setFlytDate(flsch.getFlytDate());
        book.setFlytTime(flsch.getFlytTime());

        JOptionPane.showMessageDialog(null, "Congratulations on booking with " + flsch.getFlytAirline() );
        String flytName = flsch.getFlytAirline();
        String flytFleet = flsch.getFlytFleet();
        int temp = flsch.getFlytAvlSeats();
        temp--;
        flsch.setFlytNum(flytNumTextField.getText());
        flsch.setFlytAirline(flytName);
        flsch.setFlytFleet(flytFleet);
        flsch.setFlytFrom(flytFromTextField.getText());
        flsch.setFlytTo(flytToTextField.getText());
        flsch.setFlytDate(flytDateTextField.getText());
        flsch.setFlytTime(flyTimeTextField.getText());
        flsch.setFlytAvlSeats(temp);
        bookBtn.setEnabled(false);
        modifyBookingBtn.setEnabled(true);
    }//GEN-LAST:event_bookBtnActionPerformed

    private void modifyBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBookingBtnActionPerformed
        // TODO add your handling code here:
        int selectionButton = JOptionPane.YES_NO_OPTION;
        int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure want to cancel above mentioned bookiing??","Warning",selectionButton);
        if(selectionResult == JOptionPane.YES_OPTION){
            Booking b =  bookDir.searchAccount(custNameTextField.getText());
            bookDir.deleteBooking(b);
            int temp = flsch.getFlytAvlSeats();
            temp++;
            flsch.setFlytAvlSeats(temp);
            Seats seats =  flsch.searchSeatNum(flytSeatNumTextField.getText());
            if( seats == null){
                JOptionPane.showMessageDialog(null,"Seat status update failed please contact admin");
            }else{
                seats.setSeatStatus("A");
            }

            custEmailTextField.setText("");
            custNameTextField.setText("");
            flytBookingIdTextField.setText("");
            flytNumTextField.setText("");
            flytFromTextField.setText("");
            flytToTextField.setText("");
            flytDateTextField.setText("");
            flytSeatNumTextField.setText("");
            flyTimeTextField.setText("");
            bookBtn.setEnabled(false);
            modifyBookingBtn.setEnabled(false);
        }
    }//GEN-LAST:event_modifyBookingBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aRadioBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField custEmailTextField;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JTextField flyTimeTextField;
    private javax.swing.JTextField flytBookingIdTextField;
    private javax.swing.JTextField flytDateTextField;
    private javax.swing.JTextField flytFromTextField;
    private javax.swing.JTextField flytNumTextField;
    private javax.swing.JTextField flytSeatNumTextField;
    private javax.swing.JTextField flytToTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton mRadioBtn;
    private javax.swing.JButton modifyBookingBtn;
    private javax.swing.JRadioButton wRadioBtn;
    // End of variables declaration//GEN-END:variables
}
