/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.BookingDirectory;
import Business.Customer;
import Business.FlytSchedule;
import Business.FlytScheduleDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VARSHA PREMANI
 */
public class BookingTicketsJPanel extends javax.swing.JPanel {
    private JPanel rightPanel;
    private Customer customer;
    private FlytSchedule flsch;
    private BookingDirectory bookDir;
    private FlytScheduleDirectory fschDir;
    ArrayList<FlytSchedule> resultDir;
    /**
     * Creates new form AvlFlytJPanel
     */
    public BookingTicketsJPanel(JPanel rightPanel,Customer customer, ArrayList<FlytSchedule> resultDir,BookingDirectory bookDir,FlytScheduleDirectory fschDir) {
        initComponents();
        this.rightPanel = rightPanel;
        this.bookDir =bookDir;
        this.fschDir=fschDir;
        
        this.customer =customer;
        this.resultDir=resultDir;
        populateMul();
    }
     public BookingTicketsJPanel(JPanel rightPanel,Customer customer,FlytSchedule flsch,BookingDirectory bookDir,FlytScheduleDirectory fschDir) {
        initComponents();
        this.rightPanel = rightPanel;
        this.bookDir =bookDir;
        this.fschDir=fschDir;
        this.flsch = flsch;
        this.customer =customer;
       
        populateSingle();
    }
    public void populateSingle(){
        DefaultTableModel dtm = (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);              
        Object[] row = new Object[dtm.getColumnCount()];
        row[0]=flsch;
        row[1]=flsch.getFlytAirline();
        row[2]=flsch.getFlytFleet();
        row[3]=flsch.getFlytFrom();
        row[4]=flsch.getFlytTo();
        row[5]=flsch.getFlytAvlSeats();
        row[6]=flsch.getFlytDate();
        row[7]=flsch.getFlytTime();
        row[8]=flsch.getFlyPrice();
        dtm.addRow(row);
        
    }
    
    public void populateMul(){
        DefaultTableModel dtm = (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);  
        for(FlytSchedule a : resultDir){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=a;
            row[1]=a.getFlytAirline();
            row[2]=a.getFlytFleet();
            row[3]=a.getFlytFrom();
            row[4]=a.getFlytTo();
            row[5]=a.getFlytAvlSeats();
            row[6]=a.getFlytDate();
            row[7]=a.getFlytTime();
            row[8]=a.getFlyPrice();
            dtm.addRow(row);
          }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Flights");

        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No.", "Airliner", "Fleet", "From", "To", "Available Seats", "Flight Date", "Flight Time", "Flight Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDirectory);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(nextBtn))
                .addContainerGap(452, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:

        int selectRow = tblDirectory.getSelectedRow();
        if(selectRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
        else{
            System.out.println(tblDirectory.getValueAt(selectRow, 0));
            FlytSchedule flsch = (FlytSchedule) tblDirectory.getValueAt(selectRow, 0);
            BookingDetailJPanel bdPanel = new BookingDetailJPanel(rightPanel,customer,flsch,bookDir,fschDir);
            rightPanel.add("BookingDetailJPanel",bdPanel);
            CardLayout layout = (CardLayout)rightPanel.getLayout();
            layout.next(rightPanel);
        }     
    }//GEN-LAST:event_nextBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTable tblDirectory;
    // End of variables declaration//GEN-END:variables
}
