/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.chemist.managerrole;

import business.EcoSystem;
import business.drug.Drug;
import business.enterprise.ChemistEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.HospitalEnterprise;
import business.enterprise.SupplierEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.chemist.ManagerOrganization;
import business.organization.hospital.DoctorOrganization;
import business.organization.supplier.ApproverOrganization;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import business.workqueue.WorkRequestDrugs;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import commonutils.Constants;
import static commonutils.Constants.requestBid;
import commonutils.email.SendEmail;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.supplier.approverrole.ApproverWorkAreaJPanel;
import userinterface.supplier.approverrole.AssignToManufacturer;

/**
 *
 * @author jaysh
 */
public class RequestSupplierOrSendChemistWorker extends javax.swing.JPanel {

    /**
     * Creates new form RequestSupplierOrSendChemistWorker
     */
    private JPanel userProcessContainer;
    private ManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private WorkRequestDrugs request;
    private Network network;
    private Map<String, int[]> requestOrSend;

    public RequestSupplierOrSendChemistWorker(JPanel userProcessContainer, WorkRequestDrugs request, Map<String, int[]> requestOrSend, Boolean bidFlag,
            EcoSystem system, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.ecosystem = system;
         this.network = network;
        this.enterprise = enterprise;
        if (bidFlag == Boolean.TRUE) {
            messageLabel.setText("Inventory is low, please request Supplier");
            requestSupplier.setEnabled(true);
            sendToChemistWorker.setEnabled(false);
        } else {
            messageLabel.setText("Request can be full filled");
            requestSupplier.setEnabled(false);
            sendToChemistWorker.setEnabled(true);
        }
        this.requestOrSend = requestOrSend;
        populateRequestTable(this.requestOrSend);
    }

    private void populateRequestTable(Map<String, int[]> requestOrSend) {
        workRequestJTable.getTableHeader().setFont(new Font("Segoe UI", 1, 20));
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
        for (Map.Entry<String, int[]> entry : requestOrSend.entrySet()) {
            Object[] row = new Object[4];
            row[0] = entry.getKey();
            int[] countArray = entry.getValue();
            row[1] = countArray[0];
            row[2] = countArray[1];
            row[3] = countArray[2];
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        requestSupplier = new javax.swing.JButton();
        sendToChemistWorker = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        workRequestJTable.setBackground(new java.awt.Color(153, 255, 255));
        workRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug Name", "Inventory Count", "Order Count", "Request Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setGridColor(new java.awt.Color(0, 0, 0));
        workRequestJTable.setSelectionBackground(new java.awt.Color(153, 255, 255));
        workRequestJTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(150, 130, 669, 170);

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("Decision Screen");
        title.setAlignmentX(740.0F);
        title.setAlignmentY(245.0F);
        add(title);
        title.setBounds(290, 30, 553, 48);

        requestSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestSupplier.setText("Request Supplier");
        requestSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSupplierActionPerformed(evt);
            }
        });
        add(requestSupplier);
        requestSupplier.setBounds(150, 320, 170, 31);

        sendToChemistWorker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendToChemistWorker.setText("Send To Chemist Worker");
        sendToChemistWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToChemistWorkerActionPerformed(evt);
            }
        });
        add(sendToChemistWorker);
        sendToChemistWorker.setBounds(591, 320, 229, 31);

        messageLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 255, 0));
        add(messageLabel);
        messageLabel.setBounds(210, 80, 415, 20);

        backJButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/arrow-back-icon_1_40x40.png"))); // NOI18N
        backJButton1.setContentAreaFilled(false);
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1);
        backJButton1.setBounds(20, 40, 50, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/chem.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(-400, -50, 1710, 840);
    }// </editor-fold>//GEN-END:initComponents

    private void requestSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSupplierActionPerformed
        // Send bid request to Manufacturer
        request.getEnterpriseStack().add(this.enterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ChooseSupplier", new AssignToSupplier(userProcessContainer, ecosystem, request, this.enterprise));
        layout.next(userProcessContainer);
        //log.info("Request send to supplier");
    }//GEN-LAST:event_requestSupplierActionPerformed

    private void sendToChemistWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToChemistWorkerActionPerformed
        //Update inventory of chemist
        // ChemistEnterprise chemistEnterprise = null;
        ChemistEnterprise chemistEnterprise = (ChemistEnterprise) enterprise;
//        for (Enterprise enterprise : request.getEnterpriseStack()) {
//            if (enterprise instanceof ChemistEnterprise) {
//                chemistEnterprise = (ChemistEnterprise) enterprise;
//            }
//        }
        if (chemistEnterprise != null) {
            List<Drug> drugInventoryStock = chemistEnterprise.getInventory().getDrugStock();
            //   List<Drug> drugInventoryStockSupplier = supplierEnterprise.getInventory().getDrugStock();
            List<Drug> drugOrder = request.getDrugsOrderList();
            for (Drug drug : drugOrder) {
                Drug drugInv = drugInventoryStock.stream().filter(drugIn -> (drug.getName()).equals(drugIn.getName()))
                        .findAny()
                        .orElse(null);

            //    Drug drugInvSupp = drugInventoryStockSupplier.stream().filter(drugInsup -> (drug.getName()).equals(drugInsup.getName()))
                //    .findAny()
                //    .orElse(null);
                if (drugInv != null) {
                    drugInv.setQuantity(drugInv.getQuantity() - drug.getQuantity());
                } else {
                    drugInventoryStock.add(drug);
                }
//                if (drugInvSupp != null) {
//                    drugInvSupp.setQuantity(drugInvSupp.getQuantity() - drug.getQuantity());
//                }
            }
            //Delete this order from all queues.
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof ManagerOrganization) {
                    //Remove the workrequest from this queue
                    organization.getWorkQueue().deleteWorkRequest(request);
                }
            }
            request.setStatus(Constants.resentToChemist);
            JOptionPane.showMessageDialog(null, "Order is completed");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            ManagerWorkAreaJPanel managerworkAreaJPanel = (ManagerWorkAreaJPanel) component;
            managerworkAreaJPanel.populateRequestTable();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);

            List<String> emailIDList = new ArrayList<>();
            for (Organization organization : chemistEnterprise.getOrganizationDirectory().getOrganizationList()) {
                for (UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountListValues()) {
                    emailIDList.add(userAccount.getEmailID());
                }
            }

            List<String> emailIDListPatient = new ArrayList<>();
//            HospitalEnterprise hpenterprise = (HospitalEnterprise) enterprise;
            for (Enterprise entp : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (entp instanceof HospitalEnterprise) {
                    for (Organization organization : entp.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof DoctorOrganization) {
                            for (WorkRequest wreqEmail : organization.getWorkQueue().getWorkRequestList()) {
                                if (wreqEmail.getRequestId().equals(request.getRequestId())) {
                                    emailIDListPatient.add(wreqEmail.getSender().getEmailID());
                                    System.out.println("Emails" + emailIDList);
                                    System.out.println("Emails Patients " + emailIDListPatient);
                                }
                            }
                        }

                    }
                }
            }

            //Send email to user with password.
            ExecutorService executor = Executors.newSingleThreadExecutor();

            Runnable runnableTask = () -> {
                try {
                    System.out.println("Executor task started");
                    SendEmail sendEmail = new SendEmail();
                    sendEmail.sendMailMulti(request, emailIDList);
                    sendEmail.sendMailMulti(request, emailIDListPatient);

                } catch (Exception exception) {
                    //JOptionPane.showMessageDialog(null, "We were unable to send mail to the desired recepient! Please contact system administrator");
                    exception.printStackTrace();
                }
            };

            executor.execute(runnableTask);

            executor.shutdown();

        } else {
            request.setStatus(Constants.orderCannotBeFullfilled);
            JOptionPane.showMessageDialog(null, "Order Cannot be fulfilled");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            ManagerWorkAreaJPanel managerworkAreaJPanel = (ManagerWorkAreaJPanel) component;
            managerworkAreaJPanel.populateRequestTable();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }
    }//GEN-LAST:event_sendToChemistWorkerActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton requestSupplier;
    private javax.swing.JButton sendToChemistWorker;
    private javax.swing.JLabel title;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
